-- 1) Latest regional performance snapshot
WITH latest_week AS (
    SELECT MAX(WEEK_START) AS WEEK_START
    FROM GTM_METRICS_DEMO
)
SELECT
    REGION,
    ROUND(SUM(PIPELINE_VALUE_EUR), 2) AS PIPELINE_VALUE_EUR,
    ROUND(SUM(BOOKINGS_EUR), 2) AS BOOKINGS_EUR,
    ROUND(AVG(WIN_RATE), 4) AS WIN_RATE,
    SUM(ACTIVITY_COUNT) AS ACTIVITY_COUNT,
    COUNT_IF(REQUIRES_REVIEW) AS REVIEW_ITEMS
FROM GTM_METRICS_DEMO
WHERE WEEK_START = (SELECT WEEK_START FROM latest_week)
GROUP BY REGION
ORDER BY PIPELINE_VALUE_EUR DESC;

-- 2) Explainable changes that need analyst attention
SELECT
    WEEK_START,
    REGION,
    SEGMENT,
    PRODUCT_FAMILY,
    ROUND(PIPELINE_CHANGE_4W, 4) AS PIPELINE_CHANGE_4W,
    ROUND(WIN_RATE_CHANGE_4W, 4) AS WIN_RATE_CHANGE_4W,
    EVENT_LABEL,
    EVENT_DRIVER,
    ATTENTION_SCORE
FROM GTM_METRICS_DEMO
WHERE REQUIRES_REVIEW
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY REGION
    ORDER BY WEEK_START DESC, ATTENTION_SCORE DESC
) <= 5
ORDER BY REGION, WEEK_START DESC, ATTENTION_SCORE DESC;

-- 3) Week-over-week movement using Snowflake window functions
SELECT
    WEEK_START,
    REGION,
    SUM(PIPELINE_VALUE_EUR) AS PIPELINE_VALUE_EUR,
    LAG(SUM(PIPELINE_VALUE_EUR), 1) OVER (
        PARTITION BY REGION ORDER BY WEEK_START
    ) AS PRIOR_WEEK_PIPELINE,
    DIV0(
        SUM(PIPELINE_VALUE_EUR) - LAG(SUM(PIPELINE_VALUE_EUR), 1) OVER (
            PARTITION BY REGION ORDER BY WEEK_START
        ),
        LAG(SUM(PIPELINE_VALUE_EUR), 1) OVER (
            PARTITION BY REGION ORDER BY WEEK_START
        )
    ) AS WOW_PIPELINE_CHANGE
FROM GTM_METRICS_DEMO
GROUP BY WEEK_START, REGION
ORDER BY WEEK_START, REGION;
