-- Snowflake-ready GTM demo schema.
-- Uses synthetic portfolio data only. Review database/schema/table names and privileges before execution.

CREATE TABLE IF NOT EXISTS GTM_METRICS_DEMO (
    WEEK_START DATE,
    REGION VARCHAR,
    SEGMENT VARCHAR,
    PRODUCT_FAMILY VARCHAR,
    PIPELINE_VALUE_EUR FLOAT,
    BOOKINGS_EUR FLOAT,
    WIN_RATE FLOAT,
    CONVERSION_RATE FLOAT,
    ACTIVITY_COUNT INTEGER,
    NEW_OPPORTUNITIES INTEGER,
    FORECAST_COVERAGE FLOAT,
    EVENT_LABEL VARCHAR,
    EVENT_DRIVER VARCHAR,
    DATA_CLASSIFICATION VARCHAR,
    PIPELINE_CHANGE_4W FLOAT,
    BOOKINGS_CHANGE_4W FLOAT,
    WIN_RATE_CHANGE_4W FLOAT,
    ATTENTION_SCORE FLOAT,
    REQUIRES_REVIEW BOOLEAN
);

CREATE OR REPLACE VIEW GTM_REGIONAL_WEEKLY_V AS
SELECT
    WEEK_START,
    REGION,
    SUM(PIPELINE_VALUE_EUR) AS PIPELINE_VALUE_EUR,
    SUM(BOOKINGS_EUR) AS BOOKINGS_EUR,
    AVG(WIN_RATE) AS WIN_RATE,
    SUM(ACTIVITY_COUNT) AS ACTIVITY_COUNT,
    SUM(NEW_OPPORTUNITIES) AS NEW_OPPORTUNITIES,
    AVG(ATTENTION_SCORE) AS ATTENTION_SCORE,
    COUNT_IF(REQUIRES_REVIEW) AS REVIEW_ITEMS
FROM GTM_METRICS_DEMO
GROUP BY WEEK_START, REGION;
